[pytest]
testpaths = tests
pythonpath = ./
python_files = test*.py *Test.py Test*.py
python_classes = Test*
python_functions = test*
addopts =
    -v
    -m "not network and not slow"
    --tb=short
    --strict-markers
    --durations=10
    --maxfail=25
    ; --cov src
markers =
    all: runs all tests including slow ones
    unit: marks tests as unit tests
    network: marks tests that require network access
    slow: marks tests that are slow
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning
    ignore:unclosed database <sqlite3.Connection:ResourceWarning
    ignore:Enable tracemalloc to get the object allocation traceback
    ignore:unclosed database in <sqlite3.Connection object at

env =
    APP_ENV=testing
