name: Auto Update Toolforge

on:
    push:
        branches:
            - main

concurrency:
    group: toolforge-deploy
    cancel-in-progress: false

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Test workspace
              run: |
                  echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

            - name: Copy files to server
              uses: appleboy/scp-action@v1.0.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: 22
                  source: "./"
                  target: "~/pop_repo_tmp"
                  rm: true

            - name: Deploy on Toolforge
              uses: appleboy/ssh-action@v1.2.4
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: 22
                  request_pty: true
                  script_stop: true
                  key: ${{ secrets.KEY }}
                  script: |
                      # Define the full source path of the uploaded repository
                      FULL_PATH="/home/${{ secrets.USERNAME }}/pop_repo_tmp"

                      echo ">>> Fixing Windows line endings (CRLF to LF)..."
                      find "$FULL_PATH" -type f -name "*.sh" -exec sed -i 's/\r$//' {} +

                      # Execute Stage 1: Update arwiki core repository
                      chmod +x "$FULL_PATH/toolforge/deploy_pop_repo.sh"
                      bash "$FULL_PATH/toolforge/deploy_pop_repo.sh" "$FULL_PATH"

                      echo ">>> Cleaning up temporary repository..."
                      rm -rf "$FULL_PATH"
